### ISSUE TITLE
Can't destroy the the terraform environment due to DependencyViolation

### ISSUE THREAD

**Issue by keyvaann** [phidatalab/RADAR-K8s-Infrastructure#4] opened 2023-12-04 13:50 UTC
I'm trying to destroy the environment via `terraform destroy` but I'm getting this error message after multiple attempts:
```
│ Error: deleting EC2 Subnet (subnet-0926a18c09585dd05): DependencyViolation: The subnet 'subnet-0926a18c09585dd05' has dependencies and cannot be deleted.
│ 	status code: 400, request id: 53305f8a-addd-48de-a246-d0ade3cc432c
|
│ Error: deleting EC2 Subnet (subnet-01635dae617c6f131): DependencyViolation: The subnet 'subnet-01635dae617c6f131' has dependencies and cannot be deleted.
│ 	status code: 400, request id: 4f884fc5-f4ee-4503-9e29-7c8e995e6578
|
│ Error: deleting EC2 Subnet (subnet-00353977044e645d5): DependencyViolation: The subnet 'subnet-00353977044e645d5' has dependencies and cannot be deleted.
│ 	status code: 400, request id: 1bc4c253-2f86-4d2b-8b84-ff7a5ee97298
╵```

**Comment by K1Hyve** [comment] 2023-12-04 14:08
Trying to delete the network endpoint is also blocked in the attached VPC Endpoint hasn't been removed. Deleting the Endpoint manually unblocks the operation.

**Comment by baixiac** [comment] 2023-12-05 10:30
This cascading error usually means the ENI was not freed since the associated instance was not terminated successfully during the deletion on the EKS node group. When this happens, it is essential to check what hampers the instance termination.

I will see if I can replicate that on my side.

**Comment by baixiac** [comment] 2023-12-05 11:13
I can't get any errors by running `destroy` after `apply` except for one warning from Terraform:
`Warning: EC2 Default Network ACL (acl-03a78b44033555299) not deleted, removing from state`

, which was a false positive after I checked it on the AWS console. Between `apply` and `destroy`, did you run anything such as helmfile sync and what were they?

**Comment by K1Hyve** [comment] 2023-12-05 22:50
Interesting. No I didn't run any commands between `apply` and `destroy` as long as I can remember. I have had similar issue when creating and deleting clusters with `eksctl` in CloudFormation. Maybe it has something to do with our AWS environment but I'm not sure.
Feel free to close this issue if you don't think it can't be reproduced.

**Comment by baixiac** [comment] 2023-12-07 11:07
Alright. Closing this issue. If it reoccurs, feel free to open another one with logs on instance termination.

**Closed as completed by baixiac** 2023-12-07 11:07 UTC
